// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4WsaCgx4Bx8ITE--j6pbSqLF3wsfy6TE',
    appId: '1:607405095574:web:75fe1c228acd6ccc3760b7',
    messagingSenderId: '607405095574',
    projectId: 'lockbox-386bf',
    authDomain: 'lockbox-386bf.firebaseapp.com',
    storageBucket: 'lockbox-386bf.appspot.com',
    measurementId: 'G-2NNQ6RY83Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCYp7NkE9Bx_9D3GrukP2qnng-QJaCHS4',
    appId: '1:607405095574:android:cd4f86f677de7eb83760b7',
    messagingSenderId: '607405095574',
    projectId: 'lockbox-386bf',
    storageBucket: 'lockbox-386bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBVMOhZsvnC_p5ZhqAv9CgMEt196GYqdA',
    appId: '1:607405095574:ios:f0d0a843e98f1b813760b7',
    messagingSenderId: '607405095574',
    projectId: 'lockbox-386bf',
    storageBucket: 'lockbox-386bf.appspot.com',
    iosBundleId: 'com.example.lockbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBVMOhZsvnC_p5ZhqAv9CgMEt196GYqdA',
    appId: '1:607405095574:ios:842873f69207d1d53760b7',
    messagingSenderId: '607405095574',
    projectId: 'lockbox-386bf',
    storageBucket: 'lockbox-386bf.appspot.com',
    iosBundleId: 'com.example.lockbox.RunnerTests',
  );
}
